# Generated by Django 5.1.7 on 2025-08-26 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeattendance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeDetails',
        ),
    ]
