# Generated by Django 5.1.7 on 2025-08-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employeeattendance', '0002_delete_employeedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('EmployeeName', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=1)),
                ('Marital_status', models.CharField(max_length=20)),
                ('Relative_name', models.CharField(blank=True, help_text='Father/Mother/Spouse Name', max_length=200, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('Qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('DateofBirth', models.DateField(verbose_name='Date of Birth')),
                ('DateofJoin', models.DateField(verbose_name='Date of Join')),
                ('Phone_no', models.CharField(max_length=15, unique=True)),
                ('Emergency_phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('Shift_timing', models.CharField(max_length=10)),
                ('Blood_group', models.CharField(max_length=3)),
                ('Role', models.CharField(max_length=20)),
            ],
        ),
    ]
