# Generated by Django 5.1.7 on 2025-08-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeattendance', '0004_bloodgroup_gender_maritalstatus_role_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='Gender',
            field=models.CharField(max_length=10),
        ),
    ]
