# Generated by Django 5.1.7 on 2025-08-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeattendance', '0005_alter_employeedetails_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='Employee_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
