# Generated by Django 5.1.7 on 2025-08-26 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeattendance', '0006_remove_employeedetails_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeDetails',
        ),
    ]
