# Generated by Django 5.1.7 on 2025-08-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeattendance', '0007_delete_employeedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_code', models.CharField(max_length=20, unique=True)),
                ('EmployeeName', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=20)),
                ('Marital_status', models.CharField(max_length=20)),
                ('Relative_name', models.CharField(blank=True, max_length=200, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('Qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('DateofBirth', models.DateField()),
                ('DateofJoin', models.DateField()),
                ('Phone_no', models.CharField(max_length=15)),
                ('Emergency_phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('Shift_timing', models.CharField(max_length=50)),
                ('Blood_group', models.CharField(max_length=10)),
                ('Role', models.CharField(max_length=50)),
            ],
        ),
    ]
