# Generated by Django 5.1.7 on 2025-08-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeattendance', '0008_employeedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='employee_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
