# Generated by Django 5.1.7 on 2025-08-27 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeattendance', '0010_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
