# Generated by Django 5.1.7 on 2025-08-28 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeattendance', '0015_alter_attendance_check_in_alter_attendance_check_out'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
    ]
