# Generated by Django 5.1.7 on 2025-08-28 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeattendance', '0016_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
