# Generated by Django 5.1.7 on 2025-08-28 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeattendance', '0018_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='created_at',
        ),
    ]
