# Generated by Django 5.1.7 on 2025-08-28 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeattendance', '0019_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_entry', to='employeeattendance.employeedetails')),
            ],
        ),
    ]
