# Generated by Django 5.1.7 on 2025-08-28 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeattendance', '0020_employeepassword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeePassword',
        ),
    ]
