# Generated by Django 5.1.7 on 2025-08-30 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeattendance', '0022_employeepassword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
