# Generated by Django 5.1.7 on 2025-08-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeattendance', '0024_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='Employeecode',
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
