# Generated by Django 5.1.7 on 2025-08-30 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeattendance', '0025_remove_attendance_employeecode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeepassword',
            name='employee',
        ),
        migrations.DeleteModel(
            name='EmployeeDetails',
        ),
    ]
