# Generated by Django 5.1.7 on 2025-08-30 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeattendance', '0026_remove_attendance_employee_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='BloodGroup',
        ),
        migrations.DeleteModel(
            name='EmployeePassword',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='MaritalStatus',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
