# Generated by Django 5.1.7 on 2025-08-30 05:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employeeattendance', '0027_delete_attendance_delete_bloodgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodgroupid', models.IntegerField(unique=True)),
                ('bloodgroup', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('EmployeeName', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=20)),
                ('Marital_status', models.CharField(max_length=20)),
                ('Relative_name', models.CharField(blank=True, max_length=200, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('Qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('DateofBirth', models.DateField()),
                ('DateofJoin', models.DateField()),
                ('Phone_no', models.CharField(max_length=15)),
                ('Emergency_phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('Shift_timing', models.CharField(max_length=50)),
                ('Blood_group', models.CharField(max_length=10)),
                ('Role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genderid', models.IntegerField(unique=True)),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maritalid', models.IntegerField(unique=True)),
                ('marital', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleid', models.IntegerField(unique=True)),
                ('role', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeid', models.IntegerField(unique=True)),
                ('time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_name', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(default='Absent', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeattendance.employeedetails')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=20)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_entry', to='employeeattendance.employeedetails')),
            ],
        ),
    ]
