# Generated by Django 5.1.7 on 2025-08-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeattendance', '0028_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='Aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
