# Generated by Django 5.1.7 on 2025-09-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeattendance', '0029_employeedetails_aadhaar_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeePassword',
        ),
    ]
